"use client";

import { useState } from "react";
import { IconSparkle } from "@/components/icons";

/** One-click AI case summary + next steps (PRD §5.4 / smart features). */
export function CaseSummary({ caseId }: { caseId: string }) {
  const [summary, setSummary] = useState<string | null>(null);
  const [ai, setAi] = useState(false);
  const [loading, setLoading] = useState(false);

  async function generate() {
    setLoading(true); setSummary(null);
    try {
      const res = await fetch("/api/case-summary", {
        method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ caseId }),
      });
      const d = await res.json();
      setSummary(d.summary ?? d.error ?? "Could not generate summary.");
      setAi(!!d.ai);
    } finally { setLoading(false); }
  }

  return (
    <div>
      <button type="button" onClick={generate} disabled={loading}
        className="themed flex items-center gap-2 rounded-md px-4 py-2 text-sm font-semibold btn-secondary">
        <IconSparkle size={16} /> {loading ? "Analysing…" : summary ? "Regenerate summary" : "AI case summary"}
      </button>
      {summary && (
        <div className="themed mt-3 rounded-md border p-3" style={{ borderColor: "var(--color-border-subtle)", background: "var(--color-muted-bg)" }}>
          <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed" style={{ color: "var(--color-text-primary)" }}>{summary}</pre>
          <div className="mt-2 text-[11px]" style={{ color: "var(--color-text-secondary)" }}>
            {ai ? "Generated by Claude from case records" : "Generated from case records (enable ANTHROPIC_API_KEY for AI narrative)"}
          </div>
        </div>
      )}
    </div>
  );
}
