import { NextRequest, NextResponse } from "next/server";
import { getDB, persist, uid, enqueueNotification } from "@/lib/db";

/**
 * AI Receptionist intake API (PRD §5.4 AI-1).
 * Deterministic state machine by default; if ANTHROPIC_API_KEY is set, replies
 * are generated by Claude under the same guardrails (never legal advice, never
 * fee quotes, never case data to unverified callers).
 */

type Msg = { from: "caller" | "assistant"; text: string };
type State = { step: "name" | "phone" | "matter" | "summary" | "slot" | "done"; name?: string; phone?: string; matter?: string; summary?: string };

const URGENT_WORDS = ["urgent", "detained", "arrest", "police", "custody", "tonight", "emergency", "raid", "فوری", "گرفتار"];

function classifyMatter(text: string): string {
  const t = text.toLowerCase();
  if (/(arrest|detain|police|fir|bail|custody|گرفتار)/.test(t)) return "Criminal";
  if (/(divorce|khula|custody of|maintenance|dowry|nikah|خلع|طلاق)/.test(t)) return "Family";
  if (/(property|plot|possession|rent|tenant|جائیداد)/.test(t)) return "Civil / Property";
  if (/(company|contract|recovery|cheque|invoice)/.test(t)) return "Civil / Commercial";
  return "General";
}

function nextSlot(): string {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return `${d.toISOString().slice(0, 10)} 08:30`;
}

export async function POST(req: NextRequest) {
  const { messages, state } = (await req.json()) as { messages: Msg[]; state: State | null };
  const db = await getDB();
  const s: State = state ?? { step: "name" };
  const last = messages.filter((m) => m.from === "caller").pop()?.text?.trim() ?? "";
  const urgent = messages.some((m) => m.from === "caller" && URGENT_WORDS.some((w) => m.text.toLowerCase().includes(w)));

  let reply = "";
  const newState = { ...s };

  if (messages.length === 0) {
    reply = `Assalam-o-alaikum! You've reached ${db.firm.name}. I'm the chambers' assistant — I can take your details and book a consultation, but I can't give legal advice. May I have your name?`;
    newState.step = "name";
  } else if (s.step === "name") {
    newState.name = last.slice(0, 60);
    newState.step = "phone";
    reply = `Thank you, ${newState.name}. What's the best phone number to reach you on?`;
  } else if (s.step === "phone") {
    newState.phone = last.slice(0, 20);
    newState.step = "matter";
    reply = "Noted. Briefly, what is the matter about? (e.g., a family issue, a property dispute, a criminal matter)";
  } else if (s.step === "matter") {
    newState.matter = classifyMatter(last);
    newState.summary = last.slice(0, 300);
    newState.step = "slot";
    const slot = nextSlot();
    reply = urgent
      ? `I understand — this sounds urgent. The advocate handles ${newState.matter.toLowerCase()} matters. I'm flagging this as URGENT right now and can arrange a callback ${slot.endsWith("08:30") ? "first thing tomorrow at 8:30 AM" : `at ${slot}`}. Shall I confirm? (yes/no)`
      : `Thank you. The advocate handles ${newState.matter.toLowerCase()} matters. I can book a callback for ${slot}. Shall I confirm? (yes/no)`;
  } else if (s.step === "slot") {
    const yes = /^(yes|y|haan|jee|ji|ok|confirm|هان|ہاں|جی)/i.test(last);
    newState.step = "done";
    if (yes) {
      const slot = nextSlot();
      db.inquiries.unshift({
        id: uid("q"), channel: "webchat",
        callerName: s.name ?? "Unknown caller", phone: s.phone ?? "-",
        matterType: `${s.matter}${urgent ? " — urgent" : ""}`,
        summary: s.summary ?? "", urgency: urgent ? "urgent" : "normal",
        callbackSlot: slot, status: "new",
        transcript: [...messages, { from: "assistant", text: "(callback confirmed)" }],
        createdAt: new Date().toISOString(),
      });
      await enqueueNotification({
        recipient: "Adv. Ahmed Raza (advocate WhatsApp)",
        channel: "whatsapp", template: urgent ? "urgent-inquiry" : "new-inquiry",
        payload: `${urgent ? "⚑ URGENT — " : ""}New inquiry: ${s.matter} — ${s.summary?.slice(0, 80)} · Callback ${slot} · ${s.name} ${s.phone}`,
      });
      await persist();
      reply = `Done — your callback is booked for ${slot}. ${urgent ? "Your matter has been flagged urgent and forwarded to the advocate immediately. " : ""}Is there anything else I can note for the advocate?`;
    } else {
      reply = "No problem — your details are saved and the office will reach out during working hours. Anything else I can note?";
      db.inquiries.unshift({
        id: uid("q"), channel: "webchat",
        callerName: s.name ?? "Unknown caller", phone: s.phone ?? "-",
        matterType: s.matter ?? "General", summary: s.summary ?? "",
        urgency: urgent ? "urgent" : "normal", status: "new",
        transcript: messages, createdAt: new Date().toISOString(),
      });
      await persist();
    }
  } else {
    reply = "Noted — I've added that to your inquiry. The advocate's office will be in touch. Allah Hafiz!";
  }

  // Optional LLM polish (PRD §5.4): when ANTHROPIC_API_KEY is set, Claude rephrases
  // the deterministic reply naturally in the caller's language. The state machine
  // still owns the flow, urgency logic, and record creation — guardrails stay hard-coded.
  if (process.env.ANTHROPIC_API_KEY && reply) {
    try {
      const resp = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "x-api-key": process.env.ANTHROPIC_API_KEY,
          "anthropic-version": "2023-06-01",
          "content-type": "application/json",
        },
        body: JSON.stringify({
          model: "claude-sonnet-5",
          max_tokens: 300,
          system:
            "You are a law chamber's receptionist in Pakistan. Rephrase the given reply naturally and warmly, in the same language the caller is using (English or Urdu). Preserve every fact, time, and question exactly. Never give legal advice, never quote fees, never invent information.",
          messages: [
            ...messages.slice(-6).map((m) => ({ role: m.from === "caller" ? "user" : "assistant", content: m.text })),
            { role: "user", content: `Rephrase this receptionist reply (keep all facts/questions intact): "${reply}"` },
          ],
        }),
      });
      if (resp.ok) {
        const data = await resp.json();
        const text = data?.content?.[0]?.text;
        if (typeof text === "string" && text.trim()) reply = text.trim();
      }
    } catch {
      // Fall through to the deterministic reply — the receptionist never goes down.
    }
  }

  return NextResponse.json({ reply, state: newState, urgentFlag: urgent });
}
